apiVersion: 1
datasources:
  - name: PostgreSQL-HM
    type: postgres
    access: proxy
    url: postgres:5432
    database: hm_retail
    isDefault: true
    user: hm_admin
    secureJsonData:
      password: postgres
    jsonData:
      database: hm_retail
      sslmode: disable
      postgresVersion: 1500